### ISSUE TITLE
Support recording real websites

### ISSUE THREAD

**Issue by bhackett1024** [replayio/chromium#13]
So far we've only been able to record/replay our simple e2e test pages with chromium, which have a small amount of text and nothing else.  Before we can start using our test infrastructure to exercise a variety of real websites, we need to actually be able to replay those sites when running the backend locally.

After a few days of work we're now able to record whatsmyuseragent.com, which isn't a super impressive site but does have a lot more going on than our e2e pages.

<img width="1001" alt="Screen Shot 2021-04-05 at 8 07 44 AM" src="https://user-images.githubusercontent.com/1062578/113572609-8f0de000-95e6-11eb-8361-8a09f08791b3.png">

This recording was created using playwright, which works on an unmodified chromium.

Next up are some static sites like npr.org and facebook.com, and then going through our existing playwright test harness to make sure they can all replay at least once.

**Comment by bhackett1024** [comment]
npr.org is working now:

<img width="1316" alt="Screen Shot 2021-04-07 at 6 00 59 AM" src="https://user-images.githubusercontent.com/1062578/113848629-af64a880-9766-11eb-90df-4f5c7d203bf1.png">

**Comment by bhackett1024** [comment]
The facebook news feed is working now, and after fixing https://github.com/RecordReplay/chromium/issues/15 we can use our existing playwright script to exercise it.

<img width="1489" alt="Screen Shot 2021-04-10 at 3 59 40 PM" src="https://user-images.githubusercontent.com/1062578/114283128-355a4b00-9a16-11eb-9fb0-7af8ddea5fb8.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-144](https://linear.app/replay/issue/RUN-144/support-recording-real-websites)
