### ISSUE TITLE
Support WebGL

### ISSUE THREAD

**Issue by bhackett1024** [replayio/chromium#14]
Recording pages with WebGL contexts is running into some problems where synchronous communication with the GPU process causes the main thread to fail to finish the recording.  This could be fixed, but there are likely to be other problems using WebGL and for now we are disabling it, similarly to gecko-dev (https://github.com/RecordReplay/gecko-dev/issues/58).

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-145](https://linear.app/replay/issue/RUN-145/support-webgl)
