### ISSUE TITLE
Explicitly hang onto garbage collected objects whose finalizers can trigger mismatches

### ISSUE THREAD

**Issue by bhackett1024** [replayio/chromium#17]
GCs occur at different points when recording vs. replaying, and collect different sets of objects.  This is a problem when finalizers for those objects interact with the recording --- accessing ordered locks and so forth.  Eventually we want a system that can cope with this robustly, but for now we want to prevent these finalizers from running.  Currently we do that by never doing major GCs.  This mostly works, but we're seeing a lot of OOM and scavenger related crashes.  It should be less invasive to chrome/v8's behavior and much more efficient in memory usage to allow GCs to happen normally, but have a list of all the objects with problematic finalizers which we can mark at the start of GCs and prevent them from being collected.  This is how we deal with this problem in gecko.

**Comment by bhackett1024** [comment]
Enable old space GCs: https://github.com/RecordReplay/chromium-v8/commit/dbf49fd38e6d6098450754f3bfba911cb0a0e901

**Comment by bhackett1024** [comment]
Even after restoring V8's normal GC behavior, we were still seeing scavenger crashes.  They were happening much more frequently, allowing me to track them down to https://github.com/RecordReplay/chromium-v8/issues/6.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-325](https://linear.app/replay/issue/RUN-325/explicitly-hang-onto-garbage-collected-objects-whose-finalizers-can)
