### ISSUE TITLE
error: undefined symbol: logging::CheckError::~CheckError()

### ISSUE THREAD

**Issue by datianyun** [replayio/chromium#21]
hi i am try to build this chromium on mac. but found some errors can not compiled 

ld64.lld: error: undefined symbol: logging::CheckError::~CheckError()
>>> referenced by obj/chrome/chrome_helper_app_default_executable/chrome_exe_main_mac.o

can you give me some suggestions thanks

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-149](https://linear.app/replay/issue/RUN-149/error-undefined-symbol-loggingcheckerrorcheckerror)

**Comment by Domiii** [comment]
This is future-work as of now. Might be able to tend to Chromium for Mac later in 2023.
