### ISSUE TITLE
Run in AWS Lambda

### ISSUE THREAD

**Issue by jasonLaster** [replayio/chromium#23]
The https://github.com/alixaxel/chrome-aws-lambda documents what is required to run chromium in AWS Lambda. It should be pretty easy to use this as a starting point

https://github.com/RecordReplay/gecko-dev/issues/571

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-151](https://linear.app/replay/issue/RUN-151/run-in-aws-lambda)

**Comment by gideonred** [comment]
Reopening this for public interest.

**Comment by Domiii** [comment]
We have internally closed this as a `limitation` (for now). If anyone is seriously affected by this, please feel free to reach out.
