### ISSUE TITLE
Make a more regular chromium release cadence

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/chromium#32]
Doesn't seem that we're releasing chromium regularly so it is falling out of date with driver changes

**Comment by jaril** [comment]
@ryanjduffy this is in the current sprint, but it's not clear who put it there. Was it you who assigned it to this sprint?

In any case, what's your gauge on how soon we should address this?

**Comment by ryanjduffy** [comment]
I threw in it a "future sprint" at the time to revisit it. The engflow integration with effect this so i'm going to kick it out a couple sprints to give that time to land.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-332](https://linear.app/replay/issue/RUN-332/make-a-more-regular-chromium-release-cadence)
