### ISSUE TITLE
Upload source maps

### ISSUE THREAD

**Issue by bhackett1024** [replayio/chromium#5]
Gecko uploads source map info via the protocol for any source maps it comes across while recording.  At some point we'll want to do the same thing for chromium as well, though this might not be an important issue for automated testing if we use https://github.com/RecordReplay/backend/issues/1526 to separately upload source maps.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-140](https://linear.app/replay/issue/RUN-140/upload-source-maps)
